name: Deploy Snapshot
on:
  push:
    branches:
      - dev-**
jobs:
  deploy-snapshot:
    name: Run unit-test and Deploy snapshot
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create .gpg key
        run: |
          echo $GPG_KEY_ARMOR | base64 --decode > ./release.asc
          gpg --quiet --output $GITHUB_WORKSPACE/release.gpg --dearmor ./release.asc

          sed -i -e "s,signing.keyId=,signing.keyId=$GPG_KEY_ID,g" gradle.properties
          sed -i -e "s,signing.password=,signing.password=$GPG_PASSWORD,g" gradle.properties
          sed -i -e "s,signing.secretKeyRingFile=,signing.secretKeyRingFile=$GITHUB_WORKSPACE/release.gpg,g" gradle.properties
        env:
          GPG_KEY_ARMOR: ${{ secrets.GPG_KEY_ARMOR }}
          GPG_KEY_ID: ${{ secrets.SYNCED_GPG_KEY_ID }}
          GPG_PASSWORD: ${{ secrets.SYNCED_GPG_KEY_PASSWORD }}
      - uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate cache key
        run: ./checksum.sh checksum.txt
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Run test and check code change
        run: bash ./gradlew test check assembleDebug --stacktrace
      - name: Deploy Snapshot
        run: ./gradlew clean build && ./gradlew publishReleasePublicationToMavenRepository --no-daemon --no-parallel
        env:
          mavenCentralRepositoryUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          mavenCentralRepositoryPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
